version: "3"

services:
  # webサーバ
  web:
    # コンテナ名
    container_name: web
    # image
    image: nginx:alpine
    # コンテナの中に入る
    tty: true
    # 他のコンテナ起動後に起動するように制御
    depends_on:
      - frontend
      - backend
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
    # ポート開放
    ports:
      - 80:80
      - 443:443
    # ボリューム
    volumes:
      - "./services/web/nginx.conf:/etc/nginx/nginx.conf"
      - "./services/web/conf.d:/etc/nginx/conf.d"

  # フロントエンドサーバ(vue)
  frontend:
    # コンテナ名
    container_name: frontend
    # build
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - "./projects/frontend:/frontend"
    # WORKDIR
    working_dir: /frontend
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
    # ポート開放
    ports:
      - 5001:5000

  # バックエンドサーバ(rails)
  backend: &backend
    #
    # コンテナ名
    container_name: backend
    # build
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    # コンテナの中に入る
    tty: true
    # 他のコンテナ起動後に起動するように制御
    depends_on:
      - db
    # ボリューム
    volumes:
      - "./projects/backend:/backend"
      - ./projects/db/tmp:/tmp/db
      - bundle:/usr/local/bundle:cached
    # WORKDIR
    working_dir: /backend
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: "development"
      DATABASE_HOST: "db"
      DATABASE_NAME: "sample1"
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
    # ポート開放
    ports:
      - 3000:3000
      #- 1234:1234
      #- 26162:26162

  # rubyコード補完用
  solargraph:
    <<: *backend
    #
    # コンテナ名
    container_name: solargraph
    # 起動コマンド
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    # ポート開放
    ports:
      - 8091:7658

  # DBサーバ
  db:
    # コンテナ名
    container_name: db
    # build
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    # 環境設定
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: sample1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./services/db/sql:/docker-entrypoint-initdb.d
      - ./projects/db/tmp:/tmp/db
    # ポート開放
    ports:
      - 5432:5432

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  # postgresqk
  pg_data: {}
  # bundle
  bundle: {}
