version: "3"

services:
  # webサーバ
  web:
    # コンテナ名
    container_name: web
    # image
    image: nginx:alpine
    # 他のコンテナ起動後に起動するように制御
    #    depends_on:
    #      - php
    #      - db
    # ポート開放
    ports:
      - 80:80
      - 443:443
  #    # ボリューム
  #    volumes:
  #      - "./nginx/conf.d:/etc/nginx/conf.d"
  #      - "./app:/var/www/html"

  ## フロントエンドサーバ(vue)
  #front:
  #  # コンテナ名
  #  container_name: web
  #  # image
  #  image: node:lts-alpine3.14
  #  # ポート開放
  #  ports:
  #    - 5000:5000

  # DBサーバ
  db:
    # コンテナ名
    container_name: pg_db
    # image
    image: mdillon/postgis
    # 環境設定
    environment:
      POSTGRES_DB: sample1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    tty: true
    # ボリューム
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./services/db/sql:/docker-entrypoint-initdb.d
    # ポート開放
    ports:
      - 5432:5432

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  pg_data: {}
